export const state = () => ({
    all: [
      { 
        slug: "our-ailing-planet",
        authorId: "",
        title: 'Our Ailing Planet',
        imgSrc: 'https://cdn.vuetifyjs.com/images/cards/house.jpg',
        content: 'When Vue is updating a list of elements rendered with v-for, by default it uses an “in-place patch” strategy. If the order of the data items has changed, instead of moving the DOM elements to match the order of the items, Vue will patch each element in-place and make sure it reflects what should be rendered at that particular index. This is similar to the behavior of track-by="$index" in Vue 1.x.This default mode is efficient, but only suitable when your list render output does not rely on child component state or temporary DOM state (e.g. form input values).To give Vue a hint so that it can track each node’s identity, and thus reuse and reorder existing elements, you need to provide a unique key attribute for each item:',
        tags: ['predictive', 'medicine', 'skin'],
        likes: 0,
        views: 0,
        share: {facebok:0, twitter: 10, reddit:10, whatsapp: 1, linkedin:20},
        created: '',
        readDuration: '',
        description: '',
        keywords: [],
        url: '',
        type: 'article',
      },
      { 
        slug: "our-ailing-planet",
        authorId: "",
        title: 'Our Ailing Planet',
        imgSrc: 'https://cdn.vuetifyjs.com/images/cards/house.jpg',
        content: 'When Vue is updating a list of elements rendered with v-for, by default it uses an “in-place patch” strategy. If the order of the data items has changed, instead of moving the DOM elements to match the order of the items, Vue will patch each element in-place and make sure it reflects what should be rendered at that particular index. This is similar to the behavior of track-by="$index" in Vue 1.x.This default mode is efficient, but only suitable when your list render output does not rely on child component state or temporary DOM state (e.g. form input values).To give Vue a hint so that it can track each node’s identity, and thus reuse and reorder existing elements, you need to provide a unique key attribute for each item:',
        tags: ['predictive', 'medicine', 'skin'],
        likes: 0,
        views: 0,
        share: {facebok:0, twitter: 10, reddit:10, whatsapp: 1, linkedin:20},
        created: '',
        readDuration: '',
        description: '',
        keywords: [],
        url: '',
        type: 'article',
      },
      { 
        slug: "our-ailing-planet",
        authorId: "",
        title: 'Our Ailing Planet',
        imgSrc: 'https://cdn.vuetifyjs.com/images/cards/house.jpg',
        content: 'When Vue is updating a list of elements rendered with v-for, by default it uses an “in-place patch” strategy. If the order of the data items has changed, instead of moving the DOM elements to match the order of the items, Vue will patch each element in-place and make sure it reflects what should be rendered at that particular index. This is similar to the behavior of track-by="$index" in Vue 1.x.This default mode is efficient, but only suitable when your list render output does not rely on child component state or temporary DOM state (e.g. form input values).To give Vue a hint so that it can track each node’s identity, and thus reuse and reorder existing elements, you need to provide a unique key attribute for each item:',
        tags: ['predictive', 'medicine', 'skin'],
        likes: 0,
        views: 0,
        share: {facebok:0, twitter: 10, reddit:10, whatsapp: 1, linkedin:20},
        created: '',
        readDuration: '',
        description: '',
        keywords: [],
        url: '',
        type: 'article',
      },
      { 
        slug: "our-ailing-planet",
        authorId: "",
        title: 'Our Ailing Planet',
        imgSrc: 'https://cdn.vuetifyjs.com/images/cards/house.jpg',
        content: 'When Vue is updating a list of elements rendered with v-for, by default it uses an “in-place patch” strategy. If the order of the data items has changed, instead of moving the DOM elements to match the order of the items, Vue will patch each element in-place and make sure it reflects what should be rendered at that particular index. This is similar to the behavior of track-by="$index" in Vue 1.x.This default mode is efficient, but only suitable when your list render output does not rely on child component state or temporary DOM state (e.g. form input values).To give Vue a hint so that it can track each node’s identity, and thus reuse and reorder existing elements, you need to provide a unique key attribute for each item:',
        tags: ['predictive', 'medicine', 'skin'],
        likes: 0,
        views: 0,
        share: {facebok:0, twitter: 10, reddit:10, whatsapp: 1, linkedin:20},
        created: '',
        readDuration: '',
        description: '',
        keywords: [],
        url: '',
        type: 'article',
      },
      { 
        slug: "our-ailing-planet",
        authorId: "",
        title: 'Our Ailing Planet',
        imgSrc: 'https://cdn.vuetifyjs.com/images/cards/house.jpg',
        content: 'When Vue is updating a list of elements rendered with v-for, by default it uses an “in-place patch” strategy. If the order of the data items has changed, instead of moving the DOM elements to match the order of the items, Vue will patch each element in-place and make sure it reflects what should be rendered at that particular index. This is similar to the behavior of track-by="$index" in Vue 1.x.This default mode is efficient, but only suitable when your list render output does not rely on child component state or temporary DOM state (e.g. form input values).To give Vue a hint so that it can track each node’s identity, and thus reuse and reorder existing elements, you need to provide a unique key attribute for each item:',
        tags: ['predictive', 'medicine', 'skin'],
        likes: 0,
        views: 0,
        share: {facebok:0, twitter: 10, reddit:10, whatsapp: 1, linkedin:20},
        created: '',
        readDuration: '',
        description: '',
        keywords: [],
        url: '',
        type: 'article',
      },
      { 
        slug: "our-ailing-planet",
        authorId: "",
        title: 'Our Ailing Planet',
        imgSrc: 'https://cdn.vuetifyjs.com/images/cards/house.jpg',
        content: 'When Vue is updating a list of elements rendered with v-for, by default it uses an “in-place patch” strategy. If the order of the data items has changed, instead of moving the DOM elements to match the order of the items, Vue will patch each element in-place and make sure it reflects what should be rendered at that particular index. This is similar to the behavior of track-by="$index" in Vue 1.x.This default mode is efficient, but only suitable when your list render output does not rely on child component state or temporary DOM state (e.g. form input values).To give Vue a hint so that it can track each node’s identity, and thus reuse and reorder existing elements, you need to provide a unique key attribute for each item:',
        tags: ['predictive', 'medicine', 'skin'],
        likes: 0,
        views: 0,
        share: {facebok:0, twitter: 10, reddit:10, whatsapp: 1, linkedin:20},
        created: '',
        readDuration: '',
        description: '',
        keywords: [],
        url: '',
        type: 'article',
      },
      { 
        slug: "our-ailing-planet",
        authorId: "",
        title: 'Our Ailing Planet',
        imgSrc: 'https://cdn.vuetifyjs.com/images/cards/house.jpg',
        content: 'When Vue is updating a list of elements rendered with v-for, by default it uses an “in-place patch” strategy. If the order of the data items has changed, instead of moving the DOM elements to match the order of the items, Vue will patch each element in-place and make sure it reflects what should be rendered at that particular index. This is similar to the behavior of track-by="$index" in Vue 1.x.This default mode is efficient, but only suitable when your list render output does not rely on child component state or temporary DOM state (e.g. form input values).To give Vue a hint so that it can track each node’s identity, and thus reuse and reorder existing elements, you need to provide a unique key attribute for each item:',
        tags: ['predictive', 'medicine', 'skin'],
        likes: 0,
        views: 0,
        share: {facebok:0, twitter: 10, reddit:10, whatsapp: 1, linkedin:20},
        created: '',
        readDuration: '',
        description: '',
        keywords: [],
        url: '',
        type: 'article',
      },
      { 
        slug: "our-ailing-planet",
        authorId: "",
        title: 'Our Ailing Planet',
        imgSrc: 'https://cdn.vuetifyjs.com/images/cards/house.jpg',
        content: 'When Vue is updating a list of elements rendered with v-for, by default it uses an “in-place patch” strategy. If the order of the data items has changed, instead of moving the DOM elements to match the order of the items, Vue will patch each element in-place and make sure it reflects what should be rendered at that particular index. This is similar to the behavior of track-by="$index" in Vue 1.x.This default mode is efficient, but only suitable when your list render output does not rely on child component state or temporary DOM state (e.g. form input values).To give Vue a hint so that it can track each node’s identity, and thus reuse and reorder existing elements, you need to provide a unique key attribute for each item:',
        tags: ['predictive', 'medicine', 'skin'],
        likes: 0,
        views: 0,
        share: {facebok:0, twitter: 10, reddit:10, whatsapp: 1, linkedin:20},
        created: '',
        readDuration: '',
        description: '',
        keywords: [],
        url: '',
        type: 'article',
      },
      { 
        slug: "our-ailing-planet",
        authorId: "",
        title: 'Our Ailing Planet',
        imgSrc: 'https://cdn.vuetifyjs.com/images/cards/house.jpg',
        content: 'When Vue is updating a list of elements rendered with v-for, by default it uses an “in-place patch” strategy. If the order of the data items has changed, instead of moving the DOM elements to match the order of the items, Vue will patch each element in-place and make sure it reflects what should be rendered at that particular index. This is similar to the behavior of track-by="$index" in Vue 1.x.This default mode is efficient, but only suitable when your list render output does not rely on child component state or temporary DOM state (e.g. form input values).To give Vue a hint so that it can track each node’s identity, and thus reuse and reorder existing elements, you need to provide a unique key attribute for each item:',
        tags: ['predictive', 'medicine', 'skin'],
        likes: 0,
        views: 0,
        share: {facebok:0, twitter: 10, reddit:10, whatsapp: 1, linkedin:20},
        created: '',
        readDuration: '',
        description: '',
        keywords: [],
        url: '',
        type: 'article',
      },
    ]
  })
  